CONFIG_ZMK_KEYBOARD_NAME="Kyria OLED"

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# 5 profiles (n+2)
# CONFIG_BT_MAX_CONN=7
# CONFIG_BT_MAX_PAIRED=7

# display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_BT_BAS=n

# logging
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=2000

# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
